services:
  - type: web
    name: cv-analyzer-bot
    env: node
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: OPENROUTER_KEY_1
        sync: false
      - key: OPENROUTER_KEY_2
        sync: false
      - key: OPENROUTER_KEY_3
        sync: false
      - key: OPENROUTER_KEY_FALLBACK
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: APILAYER_KEY_1
        sync: false
      - key: APILAYER_KEY_2
        sync: false
      - key: APILAYER_KEY_3
        sync: false
      - key: APILAYER_KEY_4
        sync: false
      - key: CVPARSER_KEY_1
        sync: false
      - key: CVPARSER_KEY_2
        sync: false
      - key: CVPARSER_KEY_3
        sync: false
      - key: CVPARSER_KEY_4
        sync: false
      - key: CVPARSER_API_URL
        value: https://api.cvparser-api.com/graphql
